package com.throwandthrows;

public class Test5 //case 4
{
//	public static void main(String[] args)
//	{
//		try
//		{
//			System.out.println("Hello");
//		}
//		//Compile time error
//		catch(InterruptedException e) //FULLY checked exception
//		{
//			
//		}
//	}
}
// Durga vid no. 74
// CE:Unreachable catch block for InterruptedException. This exception is never thrown from the try statement body.